# Get MySQL configuration from the cache and store as curdb
# 
# Required Args:
#   srchost: source host
#   subdomain: sub domain
#
# Prerequisites:
#   Run get-all-wp-configs
#
---
- fail: msg="srchost is not provided"
  when: srchost is undefined
- fail: msg="Facts for {{ srchost }} was not found; Run get-all-virtualhosts"
  when: hostvars[srchost] is undefined
- fail: msg="DB facts for {{ srchost }} was not found; Run get-all-wp-configs"
  when: hostvars[srchost]['db'] is undefined
- import_tasks: tasks/get_subdomain_from_user.yml
- fail: msg="DB facts for {{ domain }} was not found; Run get-all-wp-configs"
  when: hostvars[srchost]['db'][domain] is undefined
- name: Set currrent db variable
  set_fact:
    curdb: "{{ hostvars[srchost]['db'][domain] }}"
- name: Debug db
  debug:
    var: curdb
