# Get cached docroot
#
# Required Variables:
#   srchost
#   domain
#
# Prerequisites:
#   Run get-all-virtualhosts
#
# Exported Variables:
#   curdoc
---
- fail: msg="srchost is not provided"
  when: srchost is undefined
- fail: msg="domian is not provided"
  when: domain is undefined
- fail: msg="Facts for {{ srchost }} was not found; Run get-all-virtualhosts"
  when: hostvars[srchost] is undefined
- fail: msg="docroot_map for {{ srchost }} was not found; Run get-all-virtualhosts"
  when: hostvars[srchost]['docroot_map'] is undefined
- fail: msg="docroot_map for {{ domain }} was not found"
  when: hostvars[srchost]['docroot_map'][domain] is undefined
- name: Set curdoc
  set_fact:
    curdoc: "{{ hostvars[srchost]['docroot_map'][domain] }}"
- name: Debug curdoc
  debug:
    var: curdoc
