---
- name: Dump MySQL database
  hosts: bkup
  gather_facts: no
  tasks:
  # Set curdb
  - import_tasks: tasks/mysql_config.yml
  # Set dumpdst
  - import_tasks: tasks/mysqldump_file.yml
  - name: Dump MySQL database
    mysql_db:
      state: dump
      name: "{{ curdb.name }}"
      target: "{{ dumpdst }}"
      login_host: "{{ curdb.host }}"
      login_user: "{{ curdb.user }}"
      login_password: "{{ curdb.pass }}"

