---
- name: "Display the Wordpress configuration file of the specified site"
  hosts: v01
  gather_facts: no
  tasks:
  - name: Get all the virtual hosts from httpd.conf
    httpd_config:
    register: virtual_hosts
  - name: Extract the document roots
    set_fact:
      docroots: "{{ virtual_hosts | json_query('servers[*].root' ) | sort | unique  }}" 
  #- name: Set configuration paths
  # set_fact:
  #   config_paths: "{{ docroots | product(['wp-config.php']) | map('join', '/') | list }}" 
  #- name: Display the document roots of all wordpress sites
  #  debug:
  #    var: config_paths
  #- name: Check if config file exists
  #  stat:
  #    path: "{{ item }}"
  #  with_items: "{{ config_paths }}"
  #  register: exist_test
  #- name: Summarize the test results
  #  debug:
  #    msg: "{{  item.item }}: {{ item.stat.exists }}" 
  #  loop: "{{ exist_test.results }}" 
  - name: Extract the Wordpress DB configuration
    wp_config:
      root: "{{ item }}"
      category: db
    register: wpconf
    loop: "{{ docroots }}"
  - name: Display Wordpress DB configuration
    debug:
      var: item
    loop: "{{ wpconf.results }}" 
